version: '3.9'
services:
  postgres_db:
    image: postgres:14-alpine
    container_name: PostgresCont
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
  app:
    image: myorg/myapp
    ports:
      - "8080:8080"
volumes:
  postgres_db:
    driver: local

